import { useState, useEffect } from 'react';
import { useParams, Link, useNavigate } from 'react-router-dom';
import api from '../api/axios';
import Starfield from '../components/common/Starfield';
import ProgressRing from '../common/ProgressRing';
import Toast from '../components/common/Toast';
import ThemeToggle from '../components/common/ThemeToggle';
import { calculateProgress, calculateTimelineStats } from '../utils/pathUtils';
import { ResponsiveContainer, LineChart, Line, XAxis, YAxis, Tooltip, CartesianGrid } from 'recharts';

export default function PathDetail() {
  const { id } = useParams();
  const navigate = useNavigate();
  const [path, setPath] = useState(null);
  const [loading, setLoading] = useState(true);
  const [toast, setToast] = useState(null);

  useEffect(() => {
    const fetchPath = async () => {
      try {
        const { data } = await api.get(`/paths/${id}`);
        setPath(data.path);
      } catch {
        navigate('/dashboard');
      } finally {
        setLoading(false);
      }
    };
    fetchPath();
  }, [id, navigate]);

  const handleCompleteMilestone = async (stepId) => {
    try {
      const { data } = await api.patch(`/paths/${id}/milestones/${stepId}`, { completed: true });
      setPath(data.path);
      setToast({ message: 'Milestone completed!', type: 'success' });
      window.dispatchEvent(new CustomEvent('badges-updated'));
    } catch {
      setToast({ message: 'Failed to update milestone', type: 'error' });
    }
  };

  const handleExportReport = () => {
    if (!path) return;
    const stats = calculateTimelineStats(path);
    const reportText = `
=== FUTUREERA CAREER PATH REPORT ===
Goal: ${path.goalTitle}
Status: ${path.status.toUpperCase()}
Risk Level: ${path.riskLevel}
Timeline Health: ${stats.timelineHealth}
Target Duration: ${stats.targetDurationText}
Deadline: ${stats.targetCompletionDateText}
Weekly Workload: ${stats.estimatedWeeklyHours} hrs/wk
Current Pace: ${stats.currentPace}
Estimated Cost: ₹${path.estimatedCostINR.toLocaleString('en-IN')}
Estimated Annual Salary: ₹${path.estimatedOutcomeSalaryINR.toLocaleString('en-IN')}/year

ASSUMPTIONS:
${path.assumptions}

ROADMAP MILESTONES:
${path.roadmap.map((step) => `
Month ${step.month}: ${step.milestone} [${step.completed ? 'COMPLETED' : 'PENDING'}]
Tasks:
${step.tasks.map((t) => ` - ${t}`).join('\n')}
`).join('\n')}

Generated by FutureEra AI Career Path Simulator
    `.trim();

    const blob = new Blob([reportText], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${path.goalTitle.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_report.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    setToast({ message: 'Report downloaded successfully!', type: 'success' });
  };

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="spinner" style={{ width: 36, height: 36 }} />
      </div>
    );
  }

  if (!path) return null;

  const riskColors = { low: 'var(--success)', medium: 'var(--warning)', high: 'var(--danger)' };
  const formatINR = (num) => {
    if (num >= 10000000) return `₹${(num / 10000000).toFixed(1)}Cr`;
    if (num >= 100000) return `₹${(num / 100000).toFixed(1)}L`;
    return `₹${num.toLocaleString('en-IN')}`;
  };

  const progress = calculateProgress(path);
  const completedMilestones = path.roadmap.filter((m) => m.completed).length;
  const isCompleted = path.status === 'completed' || progress === 100;
  const timelineStats = calculateTimelineStats(path);

  const chartData = path.roadmap.map((step) => ({
    month: `M${step.month}`,
    progress: step.completed ? 100 : 0,
  }));

  return (
    <div className="min-h-screen relative">
      <Starfield />
      <div className="relative z-10">
        {/* Nav */}
        <nav className="flex items-center justify-between px-6 py-4 shadow-sm" style={{ background: 'var(--card)', borderBottom: '1px solid var(--border)' }}>
          <Link to="/dashboard" className="text-2xl font-extrabold text-starlight tracking-tight hover:opacity-90 transition-opacity">
            <span className="text-comet-violet">Future</span>Era
          </Link>
          <div className="flex items-center gap-3">
            <ThemeToggle />
            <button onClick={handleExportReport} className="btn-secondary text-xs py-1.5 px-3 flex items-center gap-1">
              📄 Export report
            </button>
            <Link to="/dashboard" className="btn-secondary text-xs py-1.5 px-3">← Dashboard</Link>
          </div>
        </nav>

        <div className="max-w-4xl mx-auto px-4 sm:px-6 py-8">
          {/* Header */}
          <div className="card mb-6 animate-fadeIn">
            <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
              <div>
                <h1 className="text-2xl font-extrabold text-starlight mb-2 tracking-tight">{path.goalTitle}</h1>
                <div className="flex items-center gap-2 flex-wrap">
                  <span
                    className="text-xs font-bold px-2.5 py-1 rounded-full"
                    style={{
                      color: riskColors[path.riskLevel],
                      background: `${riskColors[path.riskLevel]}18`,
                    }}
                  >
                    {path.riskLevel} risk
                  </span>
                  <span
                    className={`text-xs font-bold px-2.5 py-1 rounded-full ${
                      isCompleted
                        ? 'bg-aurora-teal text-white'
                        : 'bg-comet-violet text-white'
                    }`}
                  >
                    {isCompleted ? '✓ Completed' : `${completedMilestones}/${path.roadmap.length} milestones (${progress}%)`}
                  </span>
                  <span className="text-xs font-bold px-2.5 py-1 rounded-full border border-card-border" style={{ background: 'var(--surface-secondary)', color: 'var(--text-primary)' }}>
                    {timelineStats.timelineHealth}
                  </span>
                  <span className="text-xs font-bold px-2.5 py-1 rounded-full border border-comet-violet/30 text-comet-violet" style={{ background: 'var(--surface-secondary)' }}>
                    Pace: {timelineStats.currentPace}
                  </span>
                </div>
              </div>
              <ProgressRing progress={progress} size={80} strokeWidth={5} />
            </div>

            {/* Comprehensive Stats Grid */}
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 mt-6 pt-4" style={{ borderTop: '1px solid var(--border)' }}>
              <div>
                <p className="text-xs font-semibold text-dust-gray uppercase tracking-wider mb-1">Target Duration</p>
                <p className="text-base font-bold text-starlight">{timelineStats.targetDurationText}</p>
              </div>
              <div>
                <p className="text-xs font-semibold text-dust-gray uppercase tracking-wider mb-1">Target Deadline</p>
                <p className="text-base font-bold text-starlight">{timelineStats.targetCompletionDateText}</p>
              </div>
              <div>
                <p className="text-xs font-semibold text-dust-gray uppercase tracking-wider mb-1">Time Remaining</p>
                <p className="text-base font-bold text-starlight">{timelineStats.timeRemainingText}</p>
              </div>
              <div>
                <p className="text-xs font-semibold text-dust-gray uppercase tracking-wider mb-1">Weekly Workload</p>
                <p className="text-base font-bold text-comet-violet">{timelineStats.estimatedWeeklyHours} hrs/wk</p>
              </div>

              <div className="pt-2" style={{ borderTop: '1px solid var(--border)' }}>
                <p className="text-xs font-semibold text-dust-gray uppercase tracking-wider mb-1">Estimated Cost</p>
                <p className="text-base font-bold text-starlight">{formatINR(path.estimatedCostINR)}</p>
              </div>
              <div className="pt-2" style={{ borderTop: '1px solid var(--border)' }}>
                <p className="text-xs font-semibold text-dust-gray uppercase tracking-wider mb-1">Est. Annual Salary</p>
                <p className="text-base font-bold text-aurora-teal">{formatINR(path.estimatedOutcomeSalaryINR)}/yr</p>
              </div>
              <div className="pt-2" style={{ borderTop: '1px solid var(--border)' }}>
                <p className="text-xs font-semibold text-dust-gray uppercase tracking-wider mb-1">Time Elapsed</p>
                <p className="text-base font-bold text-starlight">{timelineStats.timeElapsedText}</p>
              </div>
              <div className="pt-2" style={{ borderTop: '1px solid var(--border)' }}>
                <p className="text-xs font-semibold text-dust-gray uppercase tracking-wider mb-1">Timeline Health</p>
                <p className="text-base font-bold text-starlight">{timelineStats.timelineHealth}</p>
              </div>
            </div>
          </div>

          {/* Assumptions */}
          <div className="card mb-6 animate-fadeIn" style={{ animationDelay: '0.1s' }}>
            <h2 className="text-sm font-bold text-solar-amber mb-2 flex items-center gap-1">⚠ Assumptions & Factors</h2>
            <p className="text-sm font-medium text-starlight leading-relaxed">{path.assumptions}</p>
          </div>

          <div className="ai-disclaimer mb-6">
            Estimates are AI-generated based on stated assumptions and general data — not guarantees. Use this as a planning aid, not a prediction.
          </div>

          {/* Progress chart */}
          <div className="card mb-6 animate-fadeIn" style={{ animationDelay: '0.2s' }}>
            <h2 className="text-base font-extrabold text-starlight mb-4">Progress overview</h2>
            <ResponsiveContainer width="100%" height={200}>
              <LineChart data={chartData}>
                <CartesianGrid strokeDasharray="3 3" stroke="var(--border)" />
                <XAxis dataKey="month" tick={{ fill: 'var(--dust-gray)', fontSize: 11 }} />
                <YAxis tick={{ fill: 'var(--dust-gray)', fontSize: 11 }} domain={[0, 100]} />
                <Tooltip
                  contentStyle={{
                    background: 'var(--card)',
                    border: '1px solid var(--border)',
                    borderRadius: '8px',
                    fontSize: '12px',
                    color: 'var(--text-primary)',
                    boxShadow: '0 4px 14px rgba(0,0,0,0.1)',
                  }}
                />
                <Line type="monotone" dataKey="progress" stroke="var(--aurora-teal)" strokeWidth={3} dot={{ fill: 'var(--aurora-teal)', r: 4 }} />
              </LineChart>
            </ResponsiveContainer>
          </div>

          {/* Roadmap timeline */}
          <div className="animate-fadeIn" style={{ animationDelay: '0.3s' }}>
            <h2 className="text-xl font-extrabold text-starlight mb-4">Roadmap</h2>
            <div className="space-y-0 relative">
              {/* Timeline line */}
              <div
                className="absolute left-[15px] top-0 bottom-0 w-[2px]"
                style={{ background: 'var(--border)' }}
              />

              {path.roadmap.map((step, i) => {
                const isCurrent = !step.completed && (i === 0 || path.roadmap[i - 1]?.completed);
                const dotColor = step.completed
                  ? 'var(--aurora-teal)'
                  : isCurrent
                  ? 'var(--comet-violet)'
                  : 'var(--dust-gray)';

                return (
                  <div key={step._id} className="relative pl-10 pb-6">
                    {/* Dot */}
                    <div
                      className="absolute left-[9px] top-1 w-[14px] h-[14px] rounded-full border-2"
                      style={{
                        borderColor: dotColor,
                        backgroundColor: step.completed ? dotColor : 'var(--card)',
                        boxShadow: isCurrent ? `0 0 12px ${dotColor}` : 'none',
                      }}
                    />

                    <div className={`card ${isCurrent ? 'animate-pulse-glow' : ''}`}>
                      <div className="flex items-start justify-between">
                        <div>
                          <span className="text-xs font-bold text-comet-violet uppercase tracking-wider">Month {step.month}</span>
                          <h3 className="text-base font-extrabold text-starlight mt-0.5">{step.milestone}</h3>
                        </div>
                        {!step.completed && (
                          <button
                            className="btn-secondary text-[11px] py-1 px-3"
                            onClick={() => handleCompleteMilestone(step._id)}
                          >
                            Mark done
                          </button>
                        )}
                        {step.completed && (
                          <span className="text-xs font-bold text-aurora-teal">✓ Done</span>
                        )}
                      </div>
                      <ul className="mt-3 space-y-1.5">
                        {step.tasks.map((task, j) => (
                          <li key={j} className="text-xs font-medium text-starlight flex items-start gap-2">
                            <span className="mt-1.5 w-1.5 h-1.5 rounded-full flex-shrink-0" style={{ background: dotColor }} />
                            {task}
                          </li>
                        ))}
                      </ul>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        </div>
      </div>

      {toast && <Toast message={toast.message} type={toast.type} onClose={() => setToast(null)} />}
    </div>
  );
}
