import { useState, useEffect } from 'react';
import { useParams, useNavigate, Link } from 'react-router-dom';
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';
import { jsPDF } from 'jspdf';
import api from '../api/axios';
import { useAuth } from '../context/AuthContext';
import Starfield from '../components/common/Starfield';
import ProgressRing from '../components/common/ProgressRing';
import Toast from '../components/common/Toast';
import ThemeToggle from '../components/common/ThemeToggle';
import { calculateProgress, calculateTimelineStats } from '../utils/pathUtils';

export default function PathDetail() {
  const { id } = useParams();
  const navigate = useNavigate();
  const { user } = useAuth();
  const [path, setPath] = useState(null);
  const [loading, setLoading] = useState(true);
  const [toast, setToast] = useState(null);

  useEffect(() => {
    const fetchPath = async () => {
      try {
        const { data } = await api.get(`/paths/${id}`);
        setPath(data.path);
      } catch {
        navigate('/dashboard');
      } finally {
        setLoading(false);
      }
    };
    fetchPath();
  }, [id, navigate]);

  const handleCompleteMilestone = async (stepId) => {
    try {
      const { data } = await api.patch(`/paths/${id}/milestones/${stepId}`, { completed: true });
      setPath(data.path);
      setToast({ message: 'Milestone completed!', type: 'success' });
      window.dispatchEvent(new CustomEvent('badges-updated'));
    } catch {
      setToast({ message: 'Failed to update milestone', type: 'error' });
    }
  };

  const handleExportReport = () => {
    if (!path) return;
<<<<<<< HEAD
    const stats = calculateTimelineStats(path);
    const reportText = `
=== FUTUREERA CAREER PATH REPORT ===
Goal: ${path.goalTitle}
Status: ${path.status.toUpperCase()}
Risk Level: ${path.riskLevel}
Timeline Health: ${stats.timelineHealth}
Target Duration: ${stats.targetDurationText}
Deadline: ${stats.targetCompletionDateText}
Weekly Workload: ${stats.estimatedWeeklyHours} hrs/wk
Current Pace: ${stats.currentPace}
Estimated Cost: ₹${path.estimatedCostINR.toLocaleString('en-IN')}
Estimated Annual Salary: ₹${path.estimatedOutcomeSalaryINR.toLocaleString('en-IN')}/year

ASSUMPTIONS:
${path.assumptions}

ROADMAP MILESTONES:
${path.roadmap.map((step) => `
Month ${step.month}: ${step.milestone} [${step.completed ? 'COMPLETED' : 'PENDING'}]
Tasks:
${step.tasks.map((t) => ` - ${t}`).join('\n')}
`).join('\n')}

Generated by FutureEra AI Career Path Simulator
    `.trim();

    const blob = new Blob([reportText], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${path.goalTitle.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_report.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    setToast({ message: 'Report downloaded successfully!', type: 'success' });
=======
    const progress = calculateProgress(path);
    const isCompleted = path.status === 'completed' || progress === 100;
    const completedMilestones = path.roadmap.filter((milestone) => milestone.completed).length;
    const doc = new jsPDF('p', 'mm', 'a4');
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 16;
    const contentWidth = pageWidth - margin * 2;
    const lineHeight = 4.2;
    let y = margin;

    const navy = [24, 27, 51];
    const ink = [29, 34, 61];
    const muted = [112, 117, 139];
    const slate = [232, 234, 242];
    const teal = [0, 188, 157];
    const amber = [222, 142, 33];

    const pdfText = (value) => String(value ?? '')
      .replace(/₹/g, 'INR ')
      .replace(/[—–]/g, '-')
      .replace(/[•·]/g, '|')
      .replace(/[✓✔⚠]/g, '')
      .replace(/[^\x20-\x7E]/g, '');

    const drawLines = (lines, x, startY, spacing) => {
      lines.forEach((line, index) => doc.text(line, x, startY + index * spacing));
    };

    const ensureSpace = (height) => {
      if (y + height > pageHeight - 18) {
        doc.addPage();
        y = margin;
      }
    };

    doc.setCharSpace(0);
    doc.setFillColor(...navy);
    doc.rect(0, 0, pageWidth, 52, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(18);
    doc.setTextColor(168, 137, 255);
    doc.text('Future', margin, 17);
    doc.setTextColor(255, 255, 255);
    doc.text('Era', margin + doc.getTextWidth('Future'), 17);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(190, 194, 211);
    doc.text('AI CAREER PATH SIMULATOR  |  PERSONAL ROADMAP', margin, 25);
    doc.text(`Generated ${new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}`, margin, 32);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(255, 255, 255);
    doc.text(pdfText(user?.name || 'Career planner'), margin, 39);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(15);
    doc.setTextColor(255, 255, 255);
    drawLines(doc.splitTextToSize(pdfText(path.goalTitle), contentWidth - 42).slice(0, 2), margin, 44, 5.5);
    doc.setFontSize(8);
    doc.setTextColor(isCompleted ? 74 : 193, isCompleted ? 221 : 169, isCompleted ? 190 : 255);
    doc.text(isCompleted ? 'COMPLETED' : 'IN PROGRESS', pageWidth - margin, 32, { align: 'right' });

    y = 61;
    doc.setFillColor(246, 247, 251);
    doc.roundedRect(margin, y, contentWidth, 34, 3, 3, 'F');
    const stats = [
      ['Progress', `${progress}%`],
      ['Duration', `${path.estimatedMonths} months`],
      ['Est. Cost', pdfText(formatINR(path.estimatedCostINR))],
      ['Projected Salary', `${pdfText(formatINR(path.estimatedOutcomeSalaryINR))}/yr`],
      ['Risk Level', path.riskLevel.toUpperCase()],
    ];
    const statWidth = contentWidth / stats.length;
    stats.forEach(([label, value], index) => {
      const statX = margin + statWidth * index + statWidth / 2;
      if (index > 0) {
        doc.setDrawColor(...slate);
        doc.line(margin + statWidth * index, y + 7, margin + statWidth * index, y + 27);
      }
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7);
      doc.setTextColor(...muted);
      doc.text(label, statX, y + 10, { align: 'center' });
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9.5);
      doc.setTextColor(...(label === 'Risk Level' ? amber : ink));
      doc.text(value, statX, y + 22, { align: 'center' });
    });

    y += 43;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(...ink);
    doc.text('ROADMAP PROGRESS', margin, y);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...muted);
    doc.text(`${completedMilestones} of ${path.roadmap.length} phases complete`, pageWidth - margin, y, { align: 'right' });
    y += 5;
    doc.setFillColor(...slate);
    doc.roundedRect(margin, y, contentWidth, 3.5, 1.75, 1.75, 'F');
    if (progress > 0) {
      doc.setFillColor(...teal);
      doc.roundedRect(margin, y, contentWidth * progress / 100, 3.5, 1.75, 1.75, 'F');
    }
    y += 15;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    const assumptionLines = doc.splitTextToSize(pdfText(path.assumptions), contentWidth - 18);
    const assumptionHeight = 17 + assumptionLines.length * lineHeight;
    ensureSpace(assumptionHeight);
    doc.setFillColor(255, 248, 235);
    doc.roundedRect(margin, y, contentWidth, assumptionHeight, 3, 3, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8.5);
    doc.setTextColor(...amber);
    doc.text('Assumptions', margin + 8, y + 8);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    doc.setTextColor(100, 90, 70);
    drawLines(assumptionLines, margin + 8, y + 14, lineHeight);
    y += assumptionHeight + 7;

    const disclaimerLines = doc.splitTextToSize('AI-generated estimates based on stated assumptions and general data. Use this report as a planning aid, not a prediction.', contentWidth - 12);
    const disclaimerHeight = 7 + disclaimerLines.length * 3.8;
    ensureSpace(disclaimerHeight);
    doc.setFillColor(243, 244, 249);
    doc.roundedRect(margin, y, contentWidth, disclaimerHeight, 3, 3, 'F');
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(7);
    doc.setTextColor(...muted);
    drawLines(disclaimerLines, margin + 6, y + 5, 3.8);
    y += disclaimerHeight + 8;

    ensureSpace(20);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(13);
    doc.setTextColor(...ink);
    doc.text('Career roadmap', margin, y);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    doc.setTextColor(...muted);
    doc.text('PHASE-BY-PHASE PLAN', pageWidth - margin, y, { align: 'right' });
    y += 8;

    path.roadmap.forEach((step) => {
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9.5);
      const titleLines = doc.splitTextToSize(pdfText(step.milestone), contentWidth - 62);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7.5);
      const taskLines = step.tasks.map((task) => doc.splitTextToSize(pdfText(task), contentWidth - 34));
      const tasksHeight = taskLines.reduce((total, lines) => total + lines.length * lineHeight + 1.5, 0);
      const cardHeight = Math.max(28, 23 + titleLines.length * lineHeight + tasksHeight);
      ensureSpace(cardHeight);

      doc.setFillColor(...(step.completed ? [235, 252, 248] : [248, 249, 253]));
      doc.roundedRect(margin, y, contentWidth, cardHeight, 3, 3, 'F');
      doc.setFillColor(...(step.completed ? teal : [151, 156, 180]));
      doc.roundedRect(margin, y, 2, cardHeight, 1, 1, 'F');
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7);
      doc.setTextColor(...muted);
      doc.text(`MONTH ${step.month}`, margin + 10, y + 7);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9.5);
      doc.setTextColor(...ink);
      drawLines(titleLines, margin + 10, y + 14, lineHeight);
      doc.setFont('helvetica', step.completed ? 'bold' : 'normal');
      doc.setFontSize(7.5);
      doc.setTextColor(...(step.completed ? teal : muted));
      doc.text(step.completed ? 'DONE' : 'PENDING', pageWidth - margin - 8, y + 9, { align: 'right' });

      let taskY = y + 21 + (titleLines.length - 1) * lineHeight;
      taskLines.forEach((lines) => {
        doc.setFillColor(...(step.completed ? teal : [200, 200, 210]));
        doc.circle(margin + 12, taskY - 1.2, 0.7, 'F');
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(7.5);
        doc.setTextColor(80, 80, 100);
        drawLines(lines, margin + 17, taskY, lineHeight);
        taskY += lines.length * lineHeight + 1.5;
      });
      y += cardHeight + 4;
    });

    const totalPages = doc.internal.getNumberOfPages();
    for (let page = 1; page <= totalPages; page += 1) {
      doc.setPage(page);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7);
      doc.setTextColor(180, 180, 190);
      doc.text(`FutureEra  |  Career path report  |  Page ${page} of ${totalPages}`, pageWidth / 2, pageHeight - 10, { align: 'center' });
    }

    const filename = `${path.goalTitle.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_report.pdf`;
    doc.save(filename);
    setToast({ message: 'Report exported as PDF! 📄', type: 'success' });
  };

  const riskColors = { low: 'var(--aurora-teal)', medium: 'var(--solar-amber)', high: 'var(--meteor-red)' };

  const formatINR = (num) => {
    if (num >= 10000000) return `₹${(num / 10000000).toFixed(1)} Cr`;
    if (num >= 100000) return `₹${(num / 100000).toFixed(1)} L`;
    return `₹${num.toLocaleString('en-IN')}`;
>>>>>>> 14cdfa8 (Update project features and configuration)
  };

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="spinner" style={{ width: 36, height: 36 }} />
      </div>
    );
  }

  if (!path) return null;

  const riskColors = { low: 'var(--success)', medium: 'var(--warning)', high: 'var(--danger)' };
  const formatINR = (num) => {
    if (num >= 10000000) return `₹${(num / 10000000).toFixed(1)}Cr`;
    if (num >= 100000) return `₹${(num / 100000).toFixed(1)}L`;
    return `₹${num.toLocaleString('en-IN')}`;
  };

  const progress = calculateProgress(path);
  const completedMilestones = path.roadmap.filter((m) => m.completed).length;
  const isCompleted = path.status === 'completed' || progress === 100;
  const timelineStats = calculateTimelineStats(path);

  const chartData = path.roadmap.map((step) => ({
    month: `M${step.month}`,
    progress: step.completed ? 100 : 0,
  }));

  return (
    <div className="min-h-screen relative">
      <Starfield />
      <div className="relative z-10">
        {/* Nav */}
        <nav className="flex items-center justify-between px-6 py-4 shadow-sm" style={{ background: 'var(--card)', borderBottom: '1px solid var(--border)' }}>
          <Link to="/dashboard" className="text-2xl font-extrabold text-starlight tracking-tight hover:opacity-90 transition-opacity">
            <span className="text-comet-violet">Future</span>Era
          </Link>
          <div className="flex items-center gap-3">
            <ThemeToggle />
            <button onClick={handleExportReport} className="btn-secondary text-xs py-1.5 px-3 flex items-center gap-1">
              📄 Export report
            </button>
            <Link to="/dashboard" className="btn-secondary text-xs py-1.5 px-3">← Dashboard</Link>
          </div>
        </nav>

        <div className="max-w-4xl mx-auto px-4 sm:px-6 py-8">
          {/* Header */}
          <div className="card mb-6 animate-fadeIn">
            <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
              <div>
                <h1 className="text-2xl font-extrabold text-starlight mb-2 tracking-tight">{path.goalTitle}</h1>
                <div className="flex items-center gap-2 flex-wrap">
                  <span
                    className="text-xs font-bold px-2.5 py-1 rounded-full"
                    style={{
                      color: riskColors[path.riskLevel],
                      background: `${riskColors[path.riskLevel]}18`,
                    }}
                  >
                    {path.riskLevel} risk
                  </span>
                  <span
                    className={`text-xs font-bold px-2.5 py-1 rounded-full ${
                      isCompleted
                        ? 'bg-aurora-teal text-white'
                        : 'bg-comet-violet text-white'
                    }`}
                  >
                    {isCompleted ? '✓ Completed' : `${completedMilestones}/${path.roadmap.length} milestones (${progress}%)`}
                  </span>
                  <span className="text-xs font-bold px-2.5 py-1 rounded-full border border-card-border" style={{ background: 'var(--surface-secondary)', color: 'var(--text-primary)' }}>
                    {timelineStats.timelineHealth}
                  </span>
                  <span className="text-xs font-bold px-2.5 py-1 rounded-full border border-comet-violet/30 text-comet-violet" style={{ background: 'var(--surface-secondary)' }}>
                    Pace: {timelineStats.currentPace}
                  </span>
                </div>
              </div>
              <ProgressRing progress={progress} size={80} strokeWidth={5} />
            </div>

            {/* Comprehensive Stats Grid */}
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 mt-6 pt-4" style={{ borderTop: '1px solid var(--border)' }}>
              <div>
                <p className="text-xs font-semibold text-dust-gray uppercase tracking-wider mb-1">Target Duration</p>
                <p className="text-base font-bold text-starlight">{timelineStats.targetDurationText}</p>
              </div>
              <div>
                <p className="text-xs font-semibold text-dust-gray uppercase tracking-wider mb-1">Target Deadline</p>
                <p className="text-base font-bold text-starlight">{timelineStats.targetCompletionDateText}</p>
              </div>
              <div>
                <p className="text-xs font-semibold text-dust-gray uppercase tracking-wider mb-1">Time Remaining</p>
                <p className="text-base font-bold text-starlight">{timelineStats.timeRemainingText}</p>
              </div>
              <div>
                <p className="text-xs font-semibold text-dust-gray uppercase tracking-wider mb-1">Weekly Workload</p>
                <p className="text-base font-bold text-comet-violet">{timelineStats.estimatedWeeklyHours} hrs/wk</p>
              </div>

              <div className="pt-2" style={{ borderTop: '1px solid var(--border)' }}>
                <p className="text-xs font-semibold text-dust-gray uppercase tracking-wider mb-1">Estimated Cost</p>
                <p className="text-base font-bold text-starlight">{formatINR(path.estimatedCostINR)}</p>
              </div>
              <div className="pt-2" style={{ borderTop: '1px solid var(--border)' }}>
                <p className="text-xs font-semibold text-dust-gray uppercase tracking-wider mb-1">Est. Annual Salary</p>
                <p className="text-base font-bold text-aurora-teal">{formatINR(path.estimatedOutcomeSalaryINR)}/yr</p>
              </div>
              <div className="pt-2" style={{ borderTop: '1px solid var(--border)' }}>
                <p className="text-xs font-semibold text-dust-gray uppercase tracking-wider mb-1">Time Elapsed</p>
                <p className="text-base font-bold text-starlight">{timelineStats.timeElapsedText}</p>
              </div>
              <div className="pt-2" style={{ borderTop: '1px solid var(--border)' }}>
                <p className="text-xs font-semibold text-dust-gray uppercase tracking-wider mb-1">Timeline Health</p>
                <p className="text-base font-bold text-starlight">{timelineStats.timelineHealth}</p>
              </div>
            </div>
          </div>

          {/* Assumptions */}
          <div className="card mb-6 animate-fadeIn" style={{ animationDelay: '0.1s' }}>
            <h2 className="text-sm font-bold text-solar-amber mb-2 flex items-center gap-1">⚠ Assumptions & Factors</h2>
            <p className="text-sm font-medium text-starlight leading-relaxed">{path.assumptions}</p>
          </div>

          <div className="ai-disclaimer mb-6">
            Estimates are AI-generated based on stated assumptions and general data — not guarantees. Use this as a planning aid, not a prediction.
          </div>

          {/* Progress chart */}
          <div className="card mb-6 animate-fadeIn" style={{ animationDelay: '0.2s' }}>
            <h2 className="text-base font-extrabold text-starlight mb-4">Progress overview</h2>
            <ResponsiveContainer width="100%" height={200}>
              <LineChart data={chartData}>
                <CartesianGrid strokeDasharray="3 3" stroke="var(--border)" />
                <XAxis dataKey="month" tick={{ fill: 'var(--dust-gray)', fontSize: 11 }} />
                <YAxis tick={{ fill: 'var(--dust-gray)', fontSize: 11 }} domain={[0, 100]} />
                <Tooltip
                  contentStyle={{
                    background: 'var(--card)',
                    border: '1px solid var(--border)',
                    borderRadius: '8px',
                    fontSize: '12px',
                    color: 'var(--text-primary)',
                    boxShadow: '0 4px 14px rgba(0,0,0,0.1)',
                  }}
                />
                <Line type="monotone" dataKey="progress" stroke="var(--aurora-teal)" strokeWidth={3} dot={{ fill: 'var(--aurora-teal)', r: 4 }} />
              </LineChart>
            </ResponsiveContainer>
          </div>

          {/* Roadmap timeline */}
          <div className="animate-fadeIn" style={{ animationDelay: '0.3s' }}>
            <h2 className="text-xl font-extrabold text-starlight mb-4">Roadmap</h2>
            <div className="space-y-0 relative">
              {/* Timeline line */}
              <div
                className="absolute left-[15px] top-0 bottom-0 w-[2px]"
                style={{ background: 'var(--border)' }}
              />

              {path.roadmap.map((step, i) => {
                const isCurrent = !step.completed && (i === 0 || path.roadmap[i - 1]?.completed);
                const dotColor = step.completed
                  ? 'var(--aurora-teal)'
                  : isCurrent
                  ? 'var(--comet-violet)'
                  : 'var(--dust-gray)';

                return (
                  <div key={step._id} className="relative pl-10 pb-6">
                    {/* Dot */}
                    <div
                      className="absolute left-[9px] top-1 w-[14px] h-[14px] rounded-full border-2"
                      style={{
                        borderColor: dotColor,
                        backgroundColor: step.completed ? dotColor : 'var(--card)',
                        boxShadow: isCurrent ? `0 0 12px ${dotColor}` : 'none',
                      }}
                    />

                    <div className={`card ${isCurrent ? 'animate-pulse-glow' : ''}`}>
                      <div className="flex items-start justify-between">
                        <div>
                          <span className="text-xs font-bold text-comet-violet uppercase tracking-wider">Month {step.month}</span>
                          <h3 className="text-base font-extrabold text-starlight mt-0.5">{step.milestone}</h3>
                        </div>
                        {!step.completed && (
                          <button
                            className="btn-secondary text-[11px] py-1 px-3"
                            onClick={() => handleCompleteMilestone(step._id)}
                          >
                            Mark done
                          </button>
                        )}
                        {step.completed && (
                          <span className="text-xs font-bold text-aurora-teal">✓ Done</span>
                        )}
                      </div>
                      <ul className="mt-3 space-y-1.5">
                        {step.tasks.map((task, j) => (
                          <li key={j} className="text-xs font-medium text-starlight flex items-start gap-2">
                            <span className="mt-1.5 w-1.5 h-1.5 rounded-full flex-shrink-0" style={{ background: dotColor }} />
                            {task}
                          </li>
                        ))}
                      </ul>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        </div>
      </div>

      {toast && <Toast message={toast.message} type={toast.type} onClose={() => setToast(null)} />}
    </div>
  );
}
